uploads = []
outputs = []

[[generated]]
id = "YzczyyCt3BJvVzAJe3BOP"
uri = "file://artifacts/z-fantasy/public/character-1.png"
type = "image"
title = "Cyberpunk anime girl companion"

[[generated]]
id = "tKRluC1W9KhrqcY0i-6s-"
uri = "file://artifacts/z-fantasy/public/character-2.png"
type = "image"
title = "Sci-fi male android companion"

[[generated]]
id = "efpa-nXALypyHdLgro7N6"
uri = "file://artifacts/z-fantasy/public/character-3.png"
type = "image"
title = "Dark goth vampire companion"
