import { pgTable, text, uuid, jsonb, integer, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const charactersTable = pgTable("characters", {
  characterId: uuid("character_id").primaryKey().defaultRandom(),
  creatorId: text("creator_id"),
  name: text("name").notNull(),
  visibility: text("visibility").notNull().default("private"),
  systemPrompt: text("system_prompt"),
  avatarUrl: text("avatar_url"),
  teaserDescription: text("teaser_description"),
  initialGreeting: text("initial_greeting"),
  tags: text("tags").array().notNull().default([]),
  genre: text("genre").notNull().default("Modern"),
  age: text("age"),
  triggerMetadataArray: jsonb("trigger_metadata_array"),
  imageSeed: text("image_seed"),
  styleDescriptor: text("style_descriptor"),
  // ── Columns that exist in production but were absent from this schema ──────
  promotionalText: text("promotional_text"),
  subGenres: text("sub_genres").array().notNull().default([]),
  statusLevel: integer("status_level").default(0),
  tagline: text("tagline"),
  background: text("background"),
  personality: text("personality"),
  regenerateCount: integer("regenerate_count").default(0),
  finalStepCompleted: boolean("final_step_completed").default(false),
  appearancePrompt: text("appearance_prompt"),
  // ── Appearance fields ──────────────────────────────────────────────────────
  hairColor: text("hair_color"),
  hairLength: text("hair_length"),
  eyeColor: text("eye_color"),
  height: text("height"),
  build: text("build"),
  skinTone: text("skin_tone"),
  species: text("species"),
  hybridSpecies: text("hybrid_species"),
  earType: text("ear_type"),
  distinguishingFeature: text("distinguishing_feature"),
  voiceTone: text("voice_tone"),
  hairstyle: text("hairstyle"),
  facialExpressionDefault: text("facial_expression_default"),
  accessory: text("accessory"),
  tailWings: text("tail_wings"),
  bodyMarkings: text("body_markings"),
  posture: text("posture"),
  colorPalette: text("color_palette"),
  occupationLook: text("occupation_look"),
  culturalStyle: text("cultural_style"),
  assSize: text("ass_size"),
  chestSize: text("chest_size"),
  cameraShotType: text("camera_shot_type"),
  viewDirection: text("view_direction"),
  cameraAngle: text("camera_angle"),
  genderBaseMesh: text("gender_base_mesh"),
  eyeDetailEnhancer: text("eye_detail_enhancer"),
  clothingMaterialFinish: text("clothing_material_finish"),
  legwearSocksStyle: text("legwear_socks_style"),
  environmentSetting: text("environment_setting"),
  lightingStyle: text("lighting_style"),
  renderingEngine: text("rendering_engine"),
  bangsStyle: text("bangs_style"),
  makeupStyle: text("makeup_style"),
  outfitFit: text("outfit_fit"),
  imageFocus: text("image_focus"),
  thighHipSize: text("thigh_hip_size"),
  skinTextureRealism: text("skin_texture_realism"),
  negativePromptsFilter: text("negative_prompts_filter"),
  outfitCleavageCut: text("outfit_cleavage_cut"),
  // ── artStyle + freeform description ───────────────────────────────────────
  artStyle: text("art_style"),
  characterDescriptionNotes: text("character_description_notes"),
});

export const insertCharacterSchema = createInsertSchema(charactersTable).omit({ characterId: true });
export type InsertCharacter = z.infer<typeof insertCharacterSchema>;
export type Character = typeof charactersTable.$inferSelect;
